name: Test
on:
  pull_request:
    branches:
    - '**'
  push:
    branches:
    - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: "12.18.3"
    - run: npm install -g yarn@1.22.5
    - run: yarn install
    - name: Re-run production build
      run: yarn run build
    - name: Verify commit is clean
      run: test -z "$(git status --porcelain)" || (git status; git diff; false)
